### ISSUE TITLE
Error in yaml + search4text.sh permission denied

### ISSUE THREAD

**Issue by JohannCR** [marcelvandongen/ha-search4text#2]
For this to work one needs to replace
```
type: vertical-stack
cards:
    type: entities
  - entities:
```
by
```
type: vertical-stack
cards:
  - type: entities
    entities:
```
in the lovelace config (then restart).

But it then fails because of an error
`Permission denied: './search4text.sh'`

Any idea how to fix this ?
Thanks
